version: '3'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --innodb_buffer_pool_size=2G
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
